Repository projet-gl2/Hashimiste, pull requests merged in 2024-02, with the labels that each got.

#1 création du squelette de jeu et des méthodes
  src/main/java/Aventure.java
  src/main/java/Jeu.java
Labels: documentation, enhancement, help wanted

#2 Ajoute les objet de la maps
  src/main/java/fr/hashimiste/Difficulte.java
  src/main/java/fr/hashimiste/maps/Grille.java
  src/main/java/fr/hashimiste/maps/Ile.java
  src/main/java/fr/hashimiste/maps/Pont.java
  src/test/java/fr/hashimiste/maps/GuiTest.java
  src/test/java/fr/hashimiste/maps/IleTest.java
  src/test/java/fr/hashimiste/maps/PontTest.java
Labels: documentation, enhancement, help wanted

#4 Damien
  .idea/.name
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/workspace.xml
  src/main/java/Direction.java
  src/main/java/Grille.java
  src/main/java/Ile.java
  src/main/java/Technique.java
Labels: enhancement

#7 Interfaces pour les différentes pages
  .gitignore
  src/main/java/Aventure.java
  src/main/java/fr/hashimiste/gui/Couleur.java
  src/main/java/fr/hashimiste/gui/Image.java
  src/main/java/fr/hashimiste/gui/Menu.java
  src/main/java/fr/hashimiste/gui/MenuParametres.java
  src/main/java/fr/hashimiste/gui/MenuProfilCreation.java
  src/main/java/fr/hashimiste/gui/MenuTechnique.java
  src/main/java/fr/hashimiste/gui/modelibre/ModeLibre.java
  src/main/java/fr/hashimiste/gui/modelibre/PreviewComponent.java
  src/main/java/fr/hashimiste/maps/Ile.java
  src/main/java/fr/hashimiste/techniques/Direction.java
  src/main/java/fr/hashimiste/techniques/Grille.java
  src/main/java/fr/hashimiste/techniques/Ile.java
  src/main/java/fr/hashimiste/techniques/Technique.java
  src/main/resources/images/icon.png
  src/main/resources/images/iconTransparent.png
  src/main/resources/images/logo.png
  src/main/resources/images/logoOriginal.png
  src/main/resources/images/logoTitre.png
  src/main/resources/images/logoTitreTransparent.png
  src/test/java/fr/hashimiste/gui/ModeLibreGui.java
Labels: documentation, enhancement
